name = "Ki"
source = "Monk"
level = "2"
action = "Passive"
cost = ""
description = """
You gain a number of ki points equal to your monk level.

Some of your ki features require your target to make a saving throw to resist the feature's effects. The saving throw DC is calculated as follows:

* Ki save DC = 8 + your proficiency bonus + your Wisdom modifier
"""
footnote = "Recovers on a Short Rest"
skip = true