name = "Patient Defense"
source = "Monk"
level = "2"
action = "Bonus Action"
cost = "1"
description = """
You can spend 1 ki point to take the Dodge action as a Bonus Action on your turn.
"""
footnote = ""
