name = "Quickened Healing"
source = "Monk"
level = "4"
action = "Action"
cost = "2"
description = """
You can spend 2 ki points and roll a Martial Arts die. You regain a number of hit points equal to the number rolled plus your proficiency bonus.
"""
footnote = ""