name = "Action Surge"
source = "Fighter"
level = "2"
action = "Passive"
cost = ""
description = """
You can push yourself beyond your normal limits for a moment. On your turn, you can take one additional Action on top of your regular Action and a possible Bonus Action.

Once you use this feature, you must finish a Short or Long Rest before you can use it again. Starting at 17th level, you can use it twice before a Rest, but only once on the same turn.
"""
footnote = "Recovers on a Short Rest"