name = "Great Weapon Fighting"
source = "Fighter"
level = "1"
action = "Passive"
cost = ""
description = """
When you roll a 1 or 2 on a damage die for an attack you make with a melee weapon that you are wielding with two hands, you can reroll the die and must use the new roll. The weapon must have the two-handed or versatile property for you to gain this benefit.
"""
footnote = ""