name = "Superiority Dice"
source = "Monster Hunter"
level = "3"
action = "Passive"
cost = ""
description = """
You have four superiority dice, which are d8s. A superiority die is expended when you use it. You regain all of your expended superiority dice when you finish a short or long rest. You gain another superiority die at 7th level and one more at 15th level.

You can expend superiority dice to gain a number of different benefits:

 * Add to a weapon attack roll.
 * Add to a weapon damage roll. Disadvantage on concentration save.
 * Add to Int, Wis, or a Cha save.
 * Add to Perception check to detect a hidden creature or object.
 * Add to Insight check to determine if someone is lying to you.
"""
footnote = "Recovers on a Short Rest"