name = "Bladesong"
source = "Bladesinging"
level = "2"
action = "Bonus Action"
cost = ""
description = """
* You gain a bonus to your AC equal to your Intelligence modifier (minimum of +1).
* Your walking speed increases by 10 feet.
* You have advantage on Dexterity (Acrobatics) checks.
* You gain a bonus to any Constitution saving throw you make to maintain your concentration on a spell. The bonus equals your Intelligence modifier (minimum of +1).

Lasts for 1 minute. You can use this feature a number of times equal to your proficiency bonus, and you regain all expended uses of it when you finish a long rest.
"""
footnote = "Recovers on a Long Rest"