name = "Action Surge"
source = "Fighter"
level = "2"
action = "Passive"
cost = ""
description = """
You can push yourself beyond your normal limits for a moment. On your turn, you can take one additional action, except the Magic action.

Once you use this feature, you must finish a Short Rest or Long Rest before you can use it again. Starting at level 17, you can use it twice before a rest but only once on a turn.
"""
footnote = "Recovers on a Short Rest"
