name = "Second Wind"
source = "Fighter"
level = "1"
action = "Bonus Action"
cost = ""
description = """
You have a limited well of physical and mental stamina that you can draw on. As a Bonus Action, you can use it to regain Hit Points equal to 1d10 + your Fighter level.

You can use this feature twice. You regain one expended use when you finish a Short Rest, and you regain all expended uses when you finish a Long Rest.

When you reach certain Fighter levels, you gain more uses of this feature, as shown in the Second Wind column of the Fighter table.
"""
footnote = "Recovers on a Short Rest"