name = "Tactical Mind"
source = "Fighter"
level = "2"
action = "Passive"
cost = ""
description = """
You have a mind for tactics and getting the upper hand on and off the battlefield. When you fail an ability check, you can expend a use of your Second Wind to push yourself toward success. Rather than regaining Hit Points, you roll 1d10 and add the number rolled to the ability check, potentially turning it into a success. If the check still fails, this use of Second Wind isn't expended.
"""
footnote = ""
