name = "Step of the Wind"
source = "Monk"
level = "2"
action = "Bonus Action"
cost = "1"
description = """
You can spend 1 ki point to take the Disengage or Dash action as a Bonus Action on your turn, and your jump distance is doubled for the turn.
"""
footnote = ""