name = "Hide"
source = ""
level = ""
action = "Action"
description = """
You try to conceal yourself. You must be Heavily Obscured or behind Three-Quarters Cover or Total Cover, and you must be out of any visible enemy's line of sight; if you can see a creature, you can discern whether it can see you.

While you are Hidden, the next time a creature might notice you, you must make a Dexterity (Stealth) check contested by their Wisdom (Perception). If you succeed, you gain the Invisible condition. As long as you remain Hidden, you will use the same Dexterity (Stealth) check result for any further enemies to notice you.

The condition ends on you immediately after any of the following occurrences: you make a sound louder than a whisper, an enemy finds you, you make an attack roll, or you cast a spell with a verbal component.
"""
footnote = ""
