name = "Magic"
source = ""
level = ""
action = "Action"
description = """
You utilize magic by casting a spell that has a casting time of an Action or by using a feature or Magic Item that requires a Magic action to be activated.

If you cast a spell that has a casting time of 1 minute or longer, you must take the Magic action on each turn of that casting, and you must maintain Concentration while you do so. If your Concentration is broken, the spell fails, but you don't expend a spell slot.
"""
footnote = ""
skip = true
