name = "Attack (Ranged)"
source = "Rogue"
level = "1"
action = "Action"
description = """
You make 1x attack with your shortbow or magic dagger.

To-Hit bonus = ___
Shortbow damage = 1d6 + ___
Dagger damage = 1d4 + ___


If this attacks hits, you can deal extra damage if either:

• You have Advantage on the attack roll.
• At least one of your allies is within 5 feet of the target.

Sneak Attack Damage = ______
"""
footnote = ""
