name = "Favored Terrain"
source = "Ranger"
level = "1"
action = "Passive"
cost = ""
description = """
Expertise on Int and Wis checks related to your favored terrain.

While traveling for 1+ hours in your favored terrain, you gain the following:

 • Difficult terrain doesn't slow your group's travel.
 • Your group can't become lost except by magical means.
 • You remain alert to danger even when engaged in another activity while traveling (such as foraging, navigating, or tracking).
 • If alone, you can move stealthily at a normal pace.
 • 2x food when foraging.
 • While tracking other creatures, you learn their exact number, sizes, and how long ago they passed through the area.
"""
footnote = ""