name = "Favored Enemy"
source = "Ranger"
level = "1"
action = "Passive"
cost = ""
description = """
You have advantage on Wisdom (Survival) checks to track your favored enemies, as well as on Intelligence checks to recall information about them.
"""
footnote = ""